owner: tiekoetter
repo: vodafone-stoerungsstatistiken

sites:
  - name: home.tiekoetter.com
    url: https://home.tiekoetter.com

status-website:
  introTitle: "Vodafone Störungsstatistiken"
  introMessage: Diese Seite prüft alle 5 Minuten ob eine Internet Störung bei Vodafone vorliegt.
  cname: vodafone-stoerungsstatistiken.tiekoetter.com
  favicon: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2020/06/tiekoetter-300x300.png
  logoUrl: https://tiekoettercom-cdn.tiekoetter.cloud/wp-content/uploads/2020/06/tiekoetter-300x300.png
  theme: light
  name: Vodafone Störungsstatistiken
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Tiekoetter.com
      href: https://www.tiekoetter.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"

commitMessages:
  commitAuthorName: "Tiekoetter Bot"
  commitAuthorEmail: "github-bot@tiekoetter.com"
